spring:
  application:
    name: yummify

  datasource:
    url: jdbc:postgresql://localhost:5432/Yummify
    username: admin
    password: admin

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  doc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /doc/swagger-ui.html

server:
  port: 8087
